apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: webapp-helm-repo
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: web-app-chart
      sourceRef:
        kind: GitRepository
        name: webapp-helm-repo
        namespace: flux-system
  values:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi